### ISSUE TITLE
[Function App] can I set multiple package?

### ISSUE THREAD

**Issue by TylorShin** [Azure/actions-workflow-samples#23]
I found that this Action-task deploy all files in the packagePath.
is there any way to deploy specific files and folders?

for example, I want to do sth like below one.
(I guess 'with' doesn't allow an array field though)
```
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.1.3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile:  ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package:
          - dist/*
          - httpEvent/*
```

or, we can ignore the useless folders and files when zipping following by `.funcignore`.
