### ISSUE TITLE
How to deploy a build folder generated during compilation outside the root repository

### ISSUE THREAD

**Issue by LuisDev99** [Azure/actions-workflow-samples#31]
I have a repository with two folders in the root repository. One is for the frontend (React) and one for the backend.

I would like to deploy a build folder thats gets generated during the workflow job when running the command "npm build". Is there anyway i can grab that auto-generated folder instead of grabbing a folder from the repository itself?

Heres my current .yaml file:

```
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
#

name: Build and deploy Node.js app to Azure Web App 


on:
  push:
    paths-ignore:
      - 'server/**'   # Only trigger the deployment if the client folder changed, soo ignore the server folder changes
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        cd client
        npm install
        npm run build  # I want to deploy the folder that this command generates! 

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'my-monolithic-repository'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService }}
        package: ./theGeneratedFolder # I want to grab the build folder that got created during this job and not grab a folder from the repository 
```

I can only deploy the build folder with the latest changes if i push it to the repository and i would like to avoid that and just deploy the folder that gets generated during this job. Sorry for my english. Thanks!

**Comment by undead85** [comment]
try with:
` package: client/build/`

**Comment by LuisDev99** [comment]
Hi @undead85! 

I did try that, but the action will go and look inside the github repository, not in the temporary folder that got generated during the compilation.

**Comment by chrisreddington** [comment]
@LuisDev99 - That sounds strange, I would expect it to look within the current folder of the runner rather than the repo. Here is something similar that I have done with an Azure .NET Core Function deployment.

```
name: Card API Main
on: 
  push:
      paths:
        - MySln.CardAPI/*
        - MySln.CardAPI/**
        - .github/workflows/cardapi-master.yaml
      branches:
        - master

env:
  AZURE_FUNCTIONAPP_NAME:  "mysln-crd-prd-func" # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'MySln.Cardapi'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.200'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: https://nuget.pkg.github.com/mygithuborganisation/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --output ./bin
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.CARD_API_NEU_PUBLISH_PROFILE }}
```

Have you tried listing the contents of the directory as part of your workflow to check that the content you're expecting is there / it's executing in the location that you think it should be? That's something that I did when creating my workflow, as the runner was trying to run in a different to location than where I thought.

I have a separate workflow where I push the contents of an npm run build --if-present to an Azure Blob Storage account as a static website. In that example, I am setting the working-directory property on my npm run build step, whereas I can see you are using cd. That might be worth exploring too?
